repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: file-contents-sorter
    - id: check-toml
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
    - id: markdownlint # Configure in .mdlrc